export type TaskPriority = 'low' | 'medium' | 'high';
export type TaskStatus = 'todo' | 'in-progress' | 'done';

export interface Task {
  id?: number; // Optional because it's auto-generated by IndexedDB
  title: string;
  description: string;
  priority: TaskPriority;
  category: string;
  status: TaskStatus;
  createdAt: Date;
}

export interface TaskFilter {
  query?: string;
  category?: string;
  status?: TaskStatus;
  priority?: TaskPriority;
}
